<?php

namespace app\models;

use yii\base\Model;
use Yii;

class ChangePasswordForm extends Model
{
    public $old_password;
    public $new_password;
    public $password_confirming;

    public function rules()
    {
        return [
            [['old_password', 'new_password', 'password_confirming'], 'required', 'message' => 'Поле пустое'],
            [
                'new_password',
                'match',
                'pattern' => '/^(?=.*\d)(?=.*[A-Z]).{6,20}$/',
                'message' => "Пароль должен содержать хотя бы 1 цифру, букву, <br /> быть длиной от 6 до 20 символов",
                'skipOnEmpty' => false
            ],
            ['password_confirming', 'compare', 'compareAttribute' => 'new_password', 'message' => 'Пароли должны совпадать'],
            ['old_password', 'findPassword'],
        ];
    }


    public function findPassword($attribute, $params)
    {
        $user = UserTinder::findOne(['id_user' => Yii::$app->user->getId()]);


        if (!$user || !Yii::$app->security->validatePassword($this->old_password, $user->password_hash))
        {
            $this->addError($attribute, 'Неправильный пароль.');
        }
    }

    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }
}